// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'downloader.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'parser.dart';
import 'tag_translator.dart';

// These functions are ignored because they are not marked as `pub`: `build_search_query_string`, `collect_viewer_urls`, `error_items`, `evict_image_cache`, `fetch_image_cached`, `sanitize_filename`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CACHE_ENGINE`, `NETWORK_CLIENT`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `deref`, `deref`, `fmt`, `initialize`, `initialize`

/// A basic health check to ensure Dart <-> Rust FFI is working
Future<String> healthCheck({required String name}) =>
    RustLib.instance.api.crateApiHealthCheck(name: name);

/// Initialize the Rust backend environments (cache dirs, connection pools)
/// enable_eh_host is kept for API compatibility but no longer used:
/// the built-in hosts feature was removed (DNS is used as-is).
Future<void> initBackend(
        {required String cacheDir, required bool enableEhHost}) =>
    RustLib.instance.api
        .crateApiInitBackend(cacheDir: cacheDir, enableEhHost: enableEhHost);

/// Sync cookies from Flutter WebView to Rust Reqwest client
Future<void> syncCookies({required String cookieString}) =>
    RustLib.instance.api.crateApiSyncCookies(cookieString: cookieString);

/// Set target site (https://e-hentai.org or https://exhentai.org)
Future<void> setSiteUrl({required String url}) =>
    RustLib.instance.api.crateApiSetSiteUrl(url: url);

/// Configure network client. Kept for API compatibility; the built-in
/// hosts feature was removed, so both flags are ignored (DNS used as-is).
Future<void> configureNetwork(
        {required bool enableEhHost, required bool enableExHost}) =>
    RustLib.instance.api.crateApiConfigureNetwork(
        enableEhHost: enableEhHost, enableExHost: enableExHost);

Future<void> downloadTagDb({required String path}) =>
    RustLib.instance.api.crateApiDownloadTagDb(path: path);

Future<void> loadTagDb({required String path}) =>
    RustLib.instance.api.crateApiLoadTagDb(path: path);

String translateTagSync({required String namespace, required String tag}) =>
    RustLib.instance.api
        .crateApiTranslateTagSync(namespace: namespace, tag: tag);

List<TagSuggestion> searchTagByChinese({required String keyword}) =>
    RustLib.instance.api.crateApiSearchTagByChinese(keyword: keyword);

/// Fetch the E-Hentai front page and parse real gallery data
/// Falls back to informative mock data on network error
Future<List<GalleryItem>> fetchFrontPage(
        {String? query, SearchOptions? options}) =>
    RustLib.instance.api.crateApiFetchFrontPage(query: query, options: options);

/// Fetch paginated gallery list (home page and search)
Future<GalleryPage> fetchGalleryList(
        {required int page,
        String? pageUrl,
        String? query,
        SearchOptions? options}) =>
    RustLib.instance.api.crateApiFetchGalleryList(
        page: page, pageUrl: pageUrl, query: query, options: options);

/// Fetch a custom gallery list (like watched, popular, toplist, favorites)
Future<GalleryPage> fetchCustomList(
        {required String path,
        required int page,
        String? pageUrl,
        String? query,
        SearchOptions? options}) =>
    RustLib.instance.api.crateApiFetchCustomList(
        path: path,
        page: page,
        pageUrl: pageUrl,
        query: query,
        options: options);

/// Fetch gallery details and preload next 3-5 pages
Future<GalleryDetail> fetchGalleryDetail({required String id}) =>
    RustLib.instance.api.crateApiFetchGalleryDetail(id: id);

/// Fetch a specific page of gallery thumbnails
Future<GalleryDetail> fetchGalleryPage(
        {required String id, required String token, required int page}) =>
    RustLib.instance.api
        .crateApiFetchGalleryPage(id: id, token: token, page: page);

/// Fetch image bytes, using L1 (Memory) + L2 (Disk) caching.
/// The global cache lock is only held for the (fast) cache read/write, never
/// across a network request, so one slow image cannot block other loads.
Future<Uint8List> getImage({required String url}) =>
    RustLib.instance.api.crateApiGetImage(url: url);

/// Fetch image bytes (L1/L2/L3 cache-aware) while reporting download
/// progress via [on_progress], called with `(downloaded_bytes, total_bytes)`
/// after each received chunk. `total` is `None` when the server omits
/// Content-Length. Cache hits report instant 100% completion.
Future<Uint8List> getImageWithProgress(
        {required String url,
        required FutureOr<void> Function(BigInt, BigInt?) onProgress}) =>
    RustLib.instance.api
        .crateApiGetImageWithProgress(url: url, onProgress: onProgress);

/// Resolves the actual image URL from an E-Hentai viewer page URL
Future<String> resolveImageUrl({required String viewerUrl}) =>
    RustLib.instance.api.crateApiResolveImageUrl(viewerUrl: viewerUrl);

Future<void> startDownload(
        {required String gid,
        required String token,
        required String title,
        required List<String> imageUrls,
        required int totalPages}) =>
    RustLib.instance.api.crateApiStartDownload(
        gid: gid,
        token: token,
        title: title,
        imageUrls: imageUrls,
        totalPages: totalPages);

Future<void> pauseDownload({required String gid}) =>
    RustLib.instance.api.crateApiPauseDownload(gid: gid);

Future<List<DownloadTask>> getDownloadTasks() =>
    RustLib.instance.api.crateApiGetDownloadTasks();

Future<void> deleteDownload({required String gid}) =>
    RustLib.instance.api.crateApiDeleteDownload(gid: gid);

/// Change the max number of galleries downloading at once (1..=8).
/// Previously this setting existed in the UI but was ignored by the Rust core.
Future<void> setDownloadConcurrency({required int n}) =>
    RustLib.instance.api.crateApiSetDownloadConcurrency(n: n);

/// Point the downloader at a new directory (the download-path setting).
Future<void> setDownloadDir({required String path}) =>
    RustLib.instance.api.crateApiSetDownloadDir(path: path);

/// Current download directory, if initialized.
Future<String?> getDownloadDir() =>
    RustLib.instance.api.crateApiGetDownloadDir();

/// Fetch the torrent list for a gallery (/gallerytorrents.php popup).
Future<List<TorrentItem>> fetchTorrents(
        {required String gid, required String token}) =>
    RustLib.instance.api.crateApiFetchTorrents(gid: gid, token: token);

/// Download a .torrent file (e-hentai: ehtracker.org/get, exhentai:
/// exhentai.org/torrent) and persist it under eh_downloads/torrents.
/// Returns the saved file path.
Future<String> downloadTorrent(
        {required String name, required String hash, required String token}) =>
    RustLib.instance.api
        .crateApiDownloadTorrent(name: name, hash: hash, token: token);

/// Add gallery to favorites
Future<String> addFavorite(
        {required String gid,
        required String token,
        required String favcat,
        required String favnote}) =>
    RustLib.instance.api.crateApiAddFavorite(
        gid: gid, token: token, favcat: favcat, favnote: favnote);

/// Post a comment to a gallery
Future<String> postComment(
        {required String gid,
        required String token,
        required String content}) =>
    RustLib.instance.api
        .crateApiPostComment(gid: gid, token: token, content: content);

/// Rate a gallery 1..5 via the web vote form (no API key required).
/// Fetches the detail page for the CSRF vote_key, then submits
/// vote_data="v{rating}" like the site's own JS does.
Future<String> voteGallery(
        {required String gid, required String token, required int rating}) =>
    RustLib.instance.api
        .crateApiVoteGallery(gid: gid, token: token, rating: rating);

/// Add a tag to the account's watched tags (My Tags), so matching galleries
/// show up on the /watched page (the app's "订阅" list). Requires login:
/// the My Tags form is only available to logged-in accounts.
Future<String> addWatchedTag({required String tag}) =>
    RustLib.instance.api.crateApiAddWatchedTag(tag: tag);

/// Vote (like/dislike) on a gallery comment.
/// `url` is the vote link parsed from the detail page HTML
/// (`...gallerycomments.php?gid=...&act=vote&comment_id=...&vote=1`).
/// Relative links are completed against the current site URL.
Future<String> voteComment({required String url}) =>
    RustLib.instance.api.crateApiVoteComment(url: url);

/// Fetch one more page of comments from the gallery detail pages.
/// Comments repeat across image pagination; callers should dedupe by
/// (author, time, content). Returns an empty vec when there are no more.
Future<List<GalleryComment>> fetchMoreComments(
        {required String gid, required String token, required int page}) =>
    RustLib.instance.api
        .crateApiFetchMoreComments(gid: gid, token: token, page: page);

/// Rate a gallery via api.php
Future<String> rateGallery(
        {required BigInt gid,
        required String token,
        required int rating,
        required BigInt apiuid,
        required String apikey}) =>
    RustLib.instance.api.crateApiRateGallery(
        gid: gid, token: token, rating: rating, apiuid: apiuid, apikey: apikey);

/// Fetch tag autocomplete suggestions
Future<String> fetchAutocomplete({required String prefix}) =>
    RustLib.instance.api.crateApiFetchAutocomplete(prefix: prefix);

class SearchOptions {
  final bool fSname;
  final bool fStags;
  final bool fSdesc;
  final int? fCats;

  const SearchOptions({
    required this.fSname,
    required this.fStags,
    required this.fSdesc,
    this.fCats,
  });

  @override
  int get hashCode =>
      fSname.hashCode ^ fStags.hashCode ^ fSdesc.hashCode ^ fCats.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchOptions &&
          runtimeType == other.runtimeType &&
          fSname == other.fSname &&
          fStags == other.fStags &&
          fSdesc == other.fSdesc &&
          fCats == other.fCats;
}
