// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class DownloadTask {
  final String gid;
  final String token;
  final String title;
  final int totalPages;
  final int downloadedPages;
  final int status;
  final String? errorMsg;

  const DownloadTask({
    required this.gid,
    required this.token,
    required this.title,
    required this.totalPages,
    required this.downloadedPages,
    required this.status,
    this.errorMsg,
  });

  @override
  int get hashCode =>
      gid.hashCode ^
      token.hashCode ^
      title.hashCode ^
      totalPages.hashCode ^
      downloadedPages.hashCode ^
      status.hashCode ^
      errorMsg.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadTask &&
          runtimeType == other.runtimeType &&
          gid == other.gid &&
          token == other.token &&
          title == other.title &&
          totalPages == other.totalPages &&
          downloadedPages == other.downloadedPages &&
          status == other.status &&
          errorMsg == other.errorMsg;
}
