// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'downloader.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'parser.dart';
import 'tag_translator.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  FutureOr<void> Function(BigInt, BigInt?)
      dco_decode_DartFn_Inputs_u_64_opt_box_autoadd_u_64_Output_unit_AnyhowException(
          dynamic raw);

  @protected
  Object dco_decode_DartOpaque(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  SearchOptions dco_decode_box_autoadd_search_options(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  DownloadTask dco_decode_download_task(dynamic raw);

  @protected
  GalleryComment dco_decode_gallery_comment(dynamic raw);

  @protected
  GalleryDetail dco_decode_gallery_detail(dynamic raw);

  @protected
  GalleryItem dco_decode_gallery_item(dynamic raw);

  @protected
  GalleryPage dco_decode_gallery_page(dynamic raw);

  @protected
  GalleryThumbnail dco_decode_gallery_thumbnail(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_isize(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<DownloadTask> dco_decode_list_download_task(dynamic raw);

  @protected
  List<GalleryComment> dco_decode_list_gallery_comment(dynamic raw);

  @protected
  List<GalleryItem> dco_decode_list_gallery_item(dynamic raw);

  @protected
  List<GalleryThumbnail> dco_decode_list_gallery_thumbnail(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<TagGroup> dco_decode_list_tag_group(dynamic raw);

  @protected
  List<TagSuggestion> dco_decode_list_tag_suggestion(dynamic raw);

  @protected
  List<TorrentItem> dco_decode_list_torrent_item(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  SearchOptions? dco_decode_opt_box_autoadd_search_options(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  SearchOptions dco_decode_search_options(dynamic raw);

  @protected
  TagGroup dco_decode_tag_group(dynamic raw);

  @protected
  TagSuggestion dco_decode_tag_suggestion(dynamic raw);

  @protected
  TorrentItem dco_decode_torrent_item(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Object sse_decode_DartOpaque(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  SearchOptions sse_decode_box_autoadd_search_options(
      SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  DownloadTask sse_decode_download_task(SseDeserializer deserializer);

  @protected
  GalleryComment sse_decode_gallery_comment(SseDeserializer deserializer);

  @protected
  GalleryDetail sse_decode_gallery_detail(SseDeserializer deserializer);

  @protected
  GalleryItem sse_decode_gallery_item(SseDeserializer deserializer);

  @protected
  GalleryPage sse_decode_gallery_page(SseDeserializer deserializer);

  @protected
  GalleryThumbnail sse_decode_gallery_thumbnail(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_isize(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<DownloadTask> sse_decode_list_download_task(
      SseDeserializer deserializer);

  @protected
  List<GalleryComment> sse_decode_list_gallery_comment(
      SseDeserializer deserializer);

  @protected
  List<GalleryItem> sse_decode_list_gallery_item(SseDeserializer deserializer);

  @protected
  List<GalleryThumbnail> sse_decode_list_gallery_thumbnail(
      SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<TagGroup> sse_decode_list_tag_group(SseDeserializer deserializer);

  @protected
  List<TagSuggestion> sse_decode_list_tag_suggestion(
      SseDeserializer deserializer);

  @protected
  List<TorrentItem> sse_decode_list_torrent_item(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  SearchOptions? sse_decode_opt_box_autoadd_search_options(
      SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  SearchOptions sse_decode_search_options(SseDeserializer deserializer);

  @protected
  TagGroup sse_decode_tag_group(SseDeserializer deserializer);

  @protected
  TagSuggestion sse_decode_tag_suggestion(SseDeserializer deserializer);

  @protected
  TorrentItem sse_decode_torrent_item(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void
      sse_encode_DartFn_Inputs_u_64_opt_box_autoadd_u_64_Output_unit_AnyhowException(
          FutureOr<void> Function(BigInt, BigInt?) self,
          SseSerializer serializer);

  @protected
  void sse_encode_DartOpaque(Object self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_search_options(
      SearchOptions self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_download_task(DownloadTask self, SseSerializer serializer);

  @protected
  void sse_encode_gallery_comment(
      GalleryComment self, SseSerializer serializer);

  @protected
  void sse_encode_gallery_detail(GalleryDetail self, SseSerializer serializer);

  @protected
  void sse_encode_gallery_item(GalleryItem self, SseSerializer serializer);

  @protected
  void sse_encode_gallery_page(GalleryPage self, SseSerializer serializer);

  @protected
  void sse_encode_gallery_thumbnail(
      GalleryThumbnail self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_isize(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_download_task(
      List<DownloadTask> self, SseSerializer serializer);

  @protected
  void sse_encode_list_gallery_comment(
      List<GalleryComment> self, SseSerializer serializer);

  @protected
  void sse_encode_list_gallery_item(
      List<GalleryItem> self, SseSerializer serializer);

  @protected
  void sse_encode_list_gallery_thumbnail(
      List<GalleryThumbnail> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_tag_group(List<TagGroup> self, SseSerializer serializer);

  @protected
  void sse_encode_list_tag_suggestion(
      List<TagSuggestion> self, SseSerializer serializer);

  @protected
  void sse_encode_list_torrent_item(
      List<TorrentItem> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_search_options(
      SearchOptions? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_search_options(SearchOptions self, SseSerializer serializer);

  @protected
  void sse_encode_tag_group(TagGroup self, SseSerializer serializer);

  @protected
  void sse_encode_tag_suggestion(TagSuggestion self, SseSerializer serializer);

  @protected
  void sse_encode_torrent_item(TorrentItem self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
