// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'downloader.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'parser.dart';
import 'tag_translator.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 838127887;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'ehviewer_rust_backend',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiAddFavorite(
      {required String gid,
      required String token,
      required String favcat,
      required String favnote});

  Future<String> crateApiAddWatchedTag({required String tag});

  Future<void> crateApiConfigureNetwork(
      {required bool enableEhHost, required bool enableExHost});

  Future<void> crateApiDeleteDownload({required String gid});

  Future<void> crateApiDownloadTagDb({required String path});

  Future<String> crateApiDownloadTorrent(
      {required String name, required String hash, required String token});

  Future<String> crateApiFetchAutocomplete({required String prefix});

  Future<GalleryPage> crateApiFetchCustomList(
      {required String path,
      required int page,
      String? pageUrl,
      String? query,
      SearchOptions? options});

  Future<List<GalleryItem>> crateApiFetchFrontPage(
      {String? query, SearchOptions? options});

  Future<GalleryDetail> crateApiFetchGalleryDetail({required String id});

  Future<GalleryPage> crateApiFetchGalleryList(
      {required int page,
      String? pageUrl,
      String? query,
      SearchOptions? options});

  Future<GalleryDetail> crateApiFetchGalleryPage(
      {required String id, required String token, required int page});

  Future<List<GalleryComment>> crateApiFetchMoreComments(
      {required String gid, required String token, required int page});

  Future<List<TorrentItem>> crateApiFetchTorrents(
      {required String gid, required String token});

  Future<String?> crateApiGetDownloadDir();

  Future<List<DownloadTask>> crateApiGetDownloadTasks();

  Future<Uint8List> crateApiGetImage({required String url});

  Future<Uint8List> crateApiGetImageWithProgress(
      {required String url,
      required FutureOr<void> Function(BigInt, BigInt?) onProgress});

  Future<String> crateApiHealthCheck({required String name});

  Future<void> crateApiInitBackend(
      {required String cacheDir, required bool enableEhHost});

  Future<void> crateApiLoadTagDb({required String path});

  Future<void> crateApiPauseDownload({required String gid});

  Future<String> crateApiPostComment(
      {required String gid, required String token, required String content});

  Future<String> crateApiRateGallery(
      {required BigInt gid,
      required String token,
      required int rating,
      required BigInt apiuid,
      required String apikey});

  Future<String> crateApiResolveImageUrl({required String viewerUrl});

  List<TagSuggestion> crateApiSearchTagByChinese({required String keyword});

  Future<void> crateApiSetDownloadConcurrency({required int n});

  Future<void> crateApiSetDownloadDir({required String path});

  Future<void> crateApiSetSiteUrl({required String url});

  Future<void> crateApiStartDownload(
      {required String gid,
      required String token,
      required String title,
      required List<String> imageUrls,
      required int totalPages});

  Future<void> crateApiSyncCookies({required String cookieString});

  String crateApiTranslateTagSync(
      {required String namespace, required String tag});

  Future<String> crateApiVoteGallery(
      {required String gid, required String token, required int rating});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiAddFavorite(
      {required String gid,
      required String token,
      required String favcat,
      required String favnote}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(gid, serializer);
        sse_encode_String(token, serializer);
        sse_encode_String(favcat, serializer);
        sse_encode_String(favnote, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiAddFavoriteConstMeta,
      argValues: [gid, token, favcat, favnote],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAddFavoriteConstMeta => const TaskConstMeta(
        debugName: "add_favorite",
        argNames: ["gid", "token", "favcat", "favnote"],
      );

  @override
  Future<String> crateApiAddWatchedTag({required String tag}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(tag, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiAddWatchedTagConstMeta,
      argValues: [tag],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAddWatchedTagConstMeta => const TaskConstMeta(
        debugName: "add_watched_tag",
        argNames: ["tag"],
      );

  @override
  Future<void> crateApiConfigureNetwork(
      {required bool enableEhHost, required bool enableExHost}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_bool(enableEhHost, serializer);
        sse_encode_bool(enableExHost, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiConfigureNetworkConstMeta,
      argValues: [enableEhHost, enableExHost],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiConfigureNetworkConstMeta => const TaskConstMeta(
        debugName: "configure_network",
        argNames: ["enableEhHost", "enableExHost"],
      );

  @override
  Future<void> crateApiDeleteDownload({required String gid}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(gid, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDeleteDownloadConstMeta,
      argValues: [gid],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDeleteDownloadConstMeta => const TaskConstMeta(
        debugName: "delete_download",
        argNames: ["gid"],
      );

  @override
  Future<void> crateApiDownloadTagDb({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDownloadTagDbConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDownloadTagDbConstMeta => const TaskConstMeta(
        debugName: "download_tag_db",
        argNames: ["path"],
      );

  @override
  Future<String> crateApiDownloadTorrent(
      {required String name, required String hash, required String token}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        sse_encode_String(hash, serializer);
        sse_encode_String(token, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDownloadTorrentConstMeta,
      argValues: [name, hash, token],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDownloadTorrentConstMeta => const TaskConstMeta(
        debugName: "download_torrent",
        argNames: ["name", "hash", "token"],
      );

  @override
  Future<String> crateApiFetchAutocomplete({required String prefix}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(prefix, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiFetchAutocompleteConstMeta,
      argValues: [prefix],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFetchAutocompleteConstMeta => const TaskConstMeta(
        debugName: "fetch_autocomplete",
        argNames: ["prefix"],
      );

  @override
  Future<GalleryPage> crateApiFetchCustomList(
      {required String path,
      required int page,
      String? pageUrl,
      String? query,
      SearchOptions? options}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_u_32(page, serializer);
        sse_encode_opt_String(pageUrl, serializer);
        sse_encode_opt_String(query, serializer);
        sse_encode_opt_box_autoadd_search_options(options, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_gallery_page,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiFetchCustomListConstMeta,
      argValues: [path, page, pageUrl, query, options],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFetchCustomListConstMeta => const TaskConstMeta(
        debugName: "fetch_custom_list",
        argNames: ["path", "page", "pageUrl", "query", "options"],
      );

  @override
  Future<List<GalleryItem>> crateApiFetchFrontPage(
      {String? query, SearchOptions? options}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_opt_String(query, serializer);
        sse_encode_opt_box_autoadd_search_options(options, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_gallery_item,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiFetchFrontPageConstMeta,
      argValues: [query, options],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFetchFrontPageConstMeta => const TaskConstMeta(
        debugName: "fetch_front_page",
        argNames: ["query", "options"],
      );

  @override
  Future<GalleryDetail> crateApiFetchGalleryDetail({required String id}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_gallery_detail,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiFetchGalleryDetailConstMeta,
      argValues: [id],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFetchGalleryDetailConstMeta => const TaskConstMeta(
        debugName: "fetch_gallery_detail",
        argNames: ["id"],
      );

  @override
  Future<GalleryPage> crateApiFetchGalleryList(
      {required int page,
      String? pageUrl,
      String? query,
      SearchOptions? options}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_32(page, serializer);
        sse_encode_opt_String(pageUrl, serializer);
        sse_encode_opt_String(query, serializer);
        sse_encode_opt_box_autoadd_search_options(options, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_gallery_page,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiFetchGalleryListConstMeta,
      argValues: [page, pageUrl, query, options],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFetchGalleryListConstMeta => const TaskConstMeta(
        debugName: "fetch_gallery_list",
        argNames: ["page", "pageUrl", "query", "options"],
      );

  @override
  Future<GalleryDetail> crateApiFetchGalleryPage(
      {required String id, required String token, required int page}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        sse_encode_String(token, serializer);
        sse_encode_u_32(page, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_gallery_detail,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiFetchGalleryPageConstMeta,
      argValues: [id, token, page],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFetchGalleryPageConstMeta => const TaskConstMeta(
        debugName: "fetch_gallery_page",
        argNames: ["id", "token", "page"],
      );

  @override
  Future<List<GalleryComment>> crateApiFetchMoreComments(
      {required String gid, required String token, required int page}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(gid, serializer);
        sse_encode_String(token, serializer);
        sse_encode_u_32(page, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_gallery_comment,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiFetchMoreCommentsConstMeta,
      argValues: [gid, token, page],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFetchMoreCommentsConstMeta => const TaskConstMeta(
        debugName: "fetch_more_comments",
        argNames: ["gid", "token", "page"],
      );

  @override
  Future<List<TorrentItem>> crateApiFetchTorrents(
      {required String gid, required String token}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(gid, serializer);
        sse_encode_String(token, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_torrent_item,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiFetchTorrentsConstMeta,
      argValues: [gid, token],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFetchTorrentsConstMeta => const TaskConstMeta(
        debugName: "fetch_torrents",
        argNames: ["gid", "token"],
      );

  @override
  Future<String?> crateApiGetDownloadDir() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetDownloadDirConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetDownloadDirConstMeta => const TaskConstMeta(
        debugName: "get_download_dir",
        argNames: [],
      );

  @override
  Future<List<DownloadTask>> crateApiGetDownloadTasks() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_download_task,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetDownloadTasksConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetDownloadTasksConstMeta => const TaskConstMeta(
        debugName: "get_download_tasks",
        argNames: [],
      );

  @override
  Future<Uint8List> crateApiGetImage({required String url}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(url, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiGetImageConstMeta,
      argValues: [url],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetImageConstMeta => const TaskConstMeta(
        debugName: "get_image",
        argNames: ["url"],
      );

  @override
  Future<Uint8List> crateApiGetImageWithProgress(
      {required String url,
      required FutureOr<void> Function(BigInt, BigInt?) onProgress}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(url, serializer);
        sse_encode_DartFn_Inputs_u_64_opt_box_autoadd_u_64_Output_unit_AnyhowException(
            onProgress, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiGetImageWithProgressConstMeta,
      argValues: [url, onProgress],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetImageWithProgressConstMeta =>
      const TaskConstMeta(
        debugName: "get_image_with_progress",
        argNames: ["url", "onProgress"],
      );

  @override
  Future<String> crateApiHealthCheck({required String name}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiHealthCheckConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiHealthCheckConstMeta => const TaskConstMeta(
        debugName: "health_check",
        argNames: ["name"],
      );

  @override
  Future<void> crateApiInitBackend(
      {required String cacheDir, required bool enableEhHost}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(cacheDir, serializer);
        sse_encode_bool(enableEhHost, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 20, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiInitBackendConstMeta,
      argValues: [cacheDir, enableEhHost],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInitBackendConstMeta => const TaskConstMeta(
        debugName: "init_backend",
        argNames: ["cacheDir", "enableEhHost"],
      );

  @override
  Future<void> crateApiLoadTagDb({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 21, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiLoadTagDbConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLoadTagDbConstMeta => const TaskConstMeta(
        debugName: "load_tag_db",
        argNames: ["path"],
      );

  @override
  Future<void> crateApiPauseDownload({required String gid}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(gid, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 22, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPauseDownloadConstMeta,
      argValues: [gid],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPauseDownloadConstMeta => const TaskConstMeta(
        debugName: "pause_download",
        argNames: ["gid"],
      );

  @override
  Future<String> crateApiPostComment(
      {required String gid, required String token, required String content}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(gid, serializer);
        sse_encode_String(token, serializer);
        sse_encode_String(content, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 23, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPostCommentConstMeta,
      argValues: [gid, token, content],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPostCommentConstMeta => const TaskConstMeta(
        debugName: "post_comment",
        argNames: ["gid", "token", "content"],
      );

  @override
  Future<String> crateApiRateGallery(
      {required BigInt gid,
      required String token,
      required int rating,
      required BigInt apiuid,
      required String apikey}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_64(gid, serializer);
        sse_encode_String(token, serializer);
        sse_encode_u_32(rating, serializer);
        sse_encode_u_64(apiuid, serializer);
        sse_encode_String(apikey, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 24, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiRateGalleryConstMeta,
      argValues: [gid, token, rating, apiuid, apikey],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiRateGalleryConstMeta => const TaskConstMeta(
        debugName: "rate_gallery",
        argNames: ["gid", "token", "rating", "apiuid", "apikey"],
      );

  @override
  Future<String> crateApiResolveImageUrl({required String viewerUrl}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(viewerUrl, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 25, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiResolveImageUrlConstMeta,
      argValues: [viewerUrl],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiResolveImageUrlConstMeta => const TaskConstMeta(
        debugName: "resolve_image_url",
        argNames: ["viewerUrl"],
      );

  @override
  List<TagSuggestion> crateApiSearchTagByChinese({required String keyword}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(keyword, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_tag_suggestion,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSearchTagByChineseConstMeta,
      argValues: [keyword],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSearchTagByChineseConstMeta => const TaskConstMeta(
        debugName: "search_tag_by_chinese",
        argNames: ["keyword"],
      );

  @override
  Future<void> crateApiSetDownloadConcurrency({required int n}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_32(n, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 27, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSetDownloadConcurrencyConstMeta,
      argValues: [n],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSetDownloadConcurrencyConstMeta =>
      const TaskConstMeta(
        debugName: "set_download_concurrency",
        argNames: ["n"],
      );

  @override
  Future<void> crateApiSetDownloadDir({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 28, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSetDownloadDirConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSetDownloadDirConstMeta => const TaskConstMeta(
        debugName: "set_download_dir",
        argNames: ["path"],
      );

  @override
  Future<void> crateApiSetSiteUrl({required String url}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(url, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 29, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSetSiteUrlConstMeta,
      argValues: [url],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSetSiteUrlConstMeta => const TaskConstMeta(
        debugName: "set_site_url",
        argNames: ["url"],
      );

  @override
  Future<void> crateApiStartDownload(
      {required String gid,
      required String token,
      required String title,
      required List<String> imageUrls,
      required int totalPages}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(gid, serializer);
        sse_encode_String(token, serializer);
        sse_encode_String(title, serializer);
        sse_encode_list_String(imageUrls, serializer);
        sse_encode_u_32(totalPages, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 30, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiStartDownloadConstMeta,
      argValues: [gid, token, title, imageUrls, totalPages],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiStartDownloadConstMeta => const TaskConstMeta(
        debugName: "start_download",
        argNames: ["gid", "token", "title", "imageUrls", "totalPages"],
      );

  @override
  Future<void> crateApiSyncCookies({required String cookieString}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(cookieString, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 31, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSyncCookiesConstMeta,
      argValues: [cookieString],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSyncCookiesConstMeta => const TaskConstMeta(
        debugName: "sync_cookies",
        argNames: ["cookieString"],
      );

  @override
  String crateApiTranslateTagSync(
      {required String namespace, required String tag}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(namespace, serializer);
        sse_encode_String(tag, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 32)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiTranslateTagSyncConstMeta,
      argValues: [namespace, tag],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTranslateTagSyncConstMeta => const TaskConstMeta(
        debugName: "translate_tag_sync",
        argNames: ["namespace", "tag"],
      );

  @override
  Future<String> crateApiVoteGallery(
      {required String gid, required String token, required int rating}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(gid, serializer);
        sse_encode_String(token, serializer);
        sse_encode_u_32(rating, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 33, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiVoteGalleryConstMeta,
      argValues: [gid, token, rating],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiVoteGalleryConstMeta => const TaskConstMeta(
        debugName: "vote_gallery",
        argNames: ["gid", "token", "rating"],
      );

  Future<void> Function(int, dynamic, dynamic)
      encode_DartFn_Inputs_u_64_opt_box_autoadd_u_64_Output_unit_AnyhowException(
          FutureOr<void> Function(BigInt, BigInt?) raw) {
    return (callId, rawArg0, rawArg1) async {
      final arg0 = dco_decode_u_64(rawArg0);
      final arg1 = dco_decode_opt_box_autoadd_u_64(rawArg1);

      Box<void>? rawOutput;
      Box<AnyhowException>? rawError;
      try {
        rawOutput = Box(await raw(arg0, arg1));
      } catch (e, s) {
        rawError = Box(AnyhowException("$e\n\n$s"));
      }

      final serializer = SseSerializer(generalizedFrbRustBinding);
      assert((rawOutput != null) ^ (rawError != null));
      if (rawOutput != null) {
        serializer.buffer.putUint8(0);
        sse_encode_unit(rawOutput.value, serializer);
      } else {
        serializer.buffer.putUint8(1);
        sse_encode_AnyhowException(rawError!.value, serializer);
      }
      final output = serializer.intoRaw();

      generalizedFrbRustBinding.dartFnDeliverOutput(
          callId: callId,
          ptr: output.ptr,
          rustVecLen: output.rustVecLen,
          dataLen: output.dataLen);
    };
  }

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  FutureOr<void> Function(BigInt, BigInt?)
      dco_decode_DartFn_Inputs_u_64_opt_box_autoadd_u_64_Output_unit_AnyhowException(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError('');
  }

  @protected
  Object dco_decode_DartOpaque(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return decodeDartOpaque(raw, generalizedFrbRustBinding);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  SearchOptions dco_decode_box_autoadd_search_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_search_options(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  DownloadTask dco_decode_download_task(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return DownloadTask(
      gid: dco_decode_String(arr[0]),
      token: dco_decode_String(arr[1]),
      title: dco_decode_String(arr[2]),
      totalPages: dco_decode_u_32(arr[3]),
      downloadedPages: dco_decode_u_32(arr[4]),
      status: dco_decode_i_32(arr[5]),
      errorMsg: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  GalleryComment dco_decode_gallery_comment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return GalleryComment(
      author: dco_decode_String(arr[0]),
      time: dco_decode_String(arr[1]),
      content: dco_decode_String(arr[2]),
    );
  }

  @protected
  GalleryDetail dco_decode_gallery_detail(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 17)
      throw Exception('unexpected arr length: expect 17 but see ${arr.length}');
    return GalleryDetail(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      titleJpn: dco_decode_String(arr[2]),
      coverUrl: dco_decode_String(arr[3]),
      uploader: dco_decode_String(arr[4]),
      rating: dco_decode_String(arr[5]),
      language: dco_decode_String(arr[6]),
      fileSize: dco_decode_String(arr[7]),
      postDate: dco_decode_String(arr[8]),
      favoritesCount: dco_decode_String(arr[9]),
      torrentCount: dco_decode_String(arr[10]),
      tagGroups: dco_decode_list_tag_group(arr[11]),
      totalPages: dco_decode_u_32(arr[12]),
      imageUrls: dco_decode_list_String(arr[13]),
      thumbnails: dco_decode_list_gallery_thumbnail(arr[14]),
      comments: dco_decode_list_gallery_comment(arr[15]),
      isFavorited: dco_decode_bool(arr[16]),
    );
  }

  @protected
  GalleryItem dco_decode_gallery_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return GalleryItem(
      gid: dco_decode_String(arr[0]),
      token: dco_decode_String(arr[1]),
      title: dco_decode_String(arr[2]),
      thumbUrl: dco_decode_String(arr[3]),
      category: dco_decode_String(arr[4]),
      uploader: dco_decode_String(arr[5]),
      postDate: dco_decode_String(arr[6]),
    );
  }

  @protected
  GalleryPage dco_decode_gallery_page(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return GalleryPage(
      items: dco_decode_list_gallery_item(arr[0]),
      nextUrl: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  GalleryThumbnail dco_decode_gallery_thumbnail(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return GalleryThumbnail(
      url: dco_decode_String(arr[0]),
      width: dco_decode_u_32(arr[1]),
      height: dco_decode_u_32(arr[2]),
      offsetX: dco_decode_u_32(arr[3]),
      offsetY: dco_decode_u_32(arr[4]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_isize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<DownloadTask> dco_decode_list_download_task(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_download_task).toList();
  }

  @protected
  List<GalleryComment> dco_decode_list_gallery_comment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_gallery_comment).toList();
  }

  @protected
  List<GalleryItem> dco_decode_list_gallery_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_gallery_item).toList();
  }

  @protected
  List<GalleryThumbnail> dco_decode_list_gallery_thumbnail(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_gallery_thumbnail).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TagGroup> dco_decode_list_tag_group(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_tag_group).toList();
  }

  @protected
  List<TagSuggestion> dco_decode_list_tag_suggestion(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_tag_suggestion).toList();
  }

  @protected
  List<TorrentItem> dco_decode_list_torrent_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_torrent_item).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  SearchOptions? dco_decode_opt_box_autoadd_search_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_search_options(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  SearchOptions dco_decode_search_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SearchOptions(
      fSname: dco_decode_bool(arr[0]),
      fStags: dco_decode_bool(arr[1]),
      fSdesc: dco_decode_bool(arr[2]),
      fCats: dco_decode_opt_box_autoadd_u_32(arr[3]),
    );
  }

  @protected
  TagGroup dco_decode_tag_group(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TagGroup(
      groupName: dco_decode_String(arr[0]),
      tags: dco_decode_list_String(arr[1]),
    );
  }

  @protected
  TagSuggestion dco_decode_tag_suggestion(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TagSuggestion(
      raw: dco_decode_String(arr[0]),
      translated: dco_decode_String(arr[1]),
    );
  }

  @protected
  TorrentItem dco_decode_torrent_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return TorrentItem(
      name: dco_decode_String(arr[0]),
      posted: dco_decode_String(arr[1]),
      sizeText: dco_decode_String(arr[2]),
      seeds: dco_decode_String(arr[3]),
      peers: dco_decode_String(arr[4]),
      downloads: dco_decode_String(arr[5]),
      uploader: dco_decode_String(arr[6]),
      hash: dco_decode_String(arr[7]),
      token: dco_decode_String(arr[8]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  Object sse_decode_DartOpaque(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_isize(deserializer);
    return decodeDartOpaque(inner, generalizedFrbRustBinding);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  SearchOptions sse_decode_box_autoadd_search_options(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_search_options(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  DownloadTask sse_decode_download_task(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_gid = sse_decode_String(deserializer);
    var var_token = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_totalPages = sse_decode_u_32(deserializer);
    var var_downloadedPages = sse_decode_u_32(deserializer);
    var var_status = sse_decode_i_32(deserializer);
    var var_errorMsg = sse_decode_opt_String(deserializer);
    return DownloadTask(
        gid: var_gid,
        token: var_token,
        title: var_title,
        totalPages: var_totalPages,
        downloadedPages: var_downloadedPages,
        status: var_status,
        errorMsg: var_errorMsg);
  }

  @protected
  GalleryComment sse_decode_gallery_comment(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_author = sse_decode_String(deserializer);
    var var_time = sse_decode_String(deserializer);
    var var_content = sse_decode_String(deserializer);
    return GalleryComment(
        author: var_author, time: var_time, content: var_content);
  }

  @protected
  GalleryDetail sse_decode_gallery_detail(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_titleJpn = sse_decode_String(deserializer);
    var var_coverUrl = sse_decode_String(deserializer);
    var var_uploader = sse_decode_String(deserializer);
    var var_rating = sse_decode_String(deserializer);
    var var_language = sse_decode_String(deserializer);
    var var_fileSize = sse_decode_String(deserializer);
    var var_postDate = sse_decode_String(deserializer);
    var var_favoritesCount = sse_decode_String(deserializer);
    var var_torrentCount = sse_decode_String(deserializer);
    var var_tagGroups = sse_decode_list_tag_group(deserializer);
    var var_totalPages = sse_decode_u_32(deserializer);
    var var_imageUrls = sse_decode_list_String(deserializer);
    var var_thumbnails = sse_decode_list_gallery_thumbnail(deserializer);
    var var_comments = sse_decode_list_gallery_comment(deserializer);
    var var_isFavorited = sse_decode_bool(deserializer);
    return GalleryDetail(
        id: var_id,
        title: var_title,
        titleJpn: var_titleJpn,
        coverUrl: var_coverUrl,
        uploader: var_uploader,
        rating: var_rating,
        language: var_language,
        fileSize: var_fileSize,
        postDate: var_postDate,
        favoritesCount: var_favoritesCount,
        torrentCount: var_torrentCount,
        tagGroups: var_tagGroups,
        totalPages: var_totalPages,
        imageUrls: var_imageUrls,
        thumbnails: var_thumbnails,
        comments: var_comments,
        isFavorited: var_isFavorited);
  }

  @protected
  GalleryItem sse_decode_gallery_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_gid = sse_decode_String(deserializer);
    var var_token = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_thumbUrl = sse_decode_String(deserializer);
    var var_category = sse_decode_String(deserializer);
    var var_uploader = sse_decode_String(deserializer);
    var var_postDate = sse_decode_String(deserializer);
    return GalleryItem(
        gid: var_gid,
        token: var_token,
        title: var_title,
        thumbUrl: var_thumbUrl,
        category: var_category,
        uploader: var_uploader,
        postDate: var_postDate);
  }

  @protected
  GalleryPage sse_decode_gallery_page(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_items = sse_decode_list_gallery_item(deserializer);
    var var_nextUrl = sse_decode_opt_String(deserializer);
    return GalleryPage(items: var_items, nextUrl: var_nextUrl);
  }

  @protected
  GalleryThumbnail sse_decode_gallery_thumbnail(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_url = sse_decode_String(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_offsetX = sse_decode_u_32(deserializer);
    var var_offsetY = sse_decode_u_32(deserializer);
    return GalleryThumbnail(
        url: var_url,
        width: var_width,
        height: var_height,
        offsetX: var_offsetX,
        offsetY: var_offsetY);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_isize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<DownloadTask> sse_decode_list_download_task(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DownloadTask>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_download_task(deserializer));
    }
    return ans_;
  }

  @protected
  List<GalleryComment> sse_decode_list_gallery_comment(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <GalleryComment>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_gallery_comment(deserializer));
    }
    return ans_;
  }

  @protected
  List<GalleryItem> sse_decode_list_gallery_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <GalleryItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_gallery_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<GalleryThumbnail> sse_decode_list_gallery_thumbnail(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <GalleryThumbnail>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_gallery_thumbnail(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TagGroup> sse_decode_list_tag_group(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TagGroup>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_tag_group(deserializer));
    }
    return ans_;
  }

  @protected
  List<TagSuggestion> sse_decode_list_tag_suggestion(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TagSuggestion>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_tag_suggestion(deserializer));
    }
    return ans_;
  }

  @protected
  List<TorrentItem> sse_decode_list_torrent_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TorrentItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_torrent_item(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SearchOptions? sse_decode_opt_box_autoadd_search_options(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_search_options(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SearchOptions sse_decode_search_options(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fSname = sse_decode_bool(deserializer);
    var var_fStags = sse_decode_bool(deserializer);
    var var_fSdesc = sse_decode_bool(deserializer);
    var var_fCats = sse_decode_opt_box_autoadd_u_32(deserializer);
    return SearchOptions(
        fSname: var_fSname,
        fStags: var_fStags,
        fSdesc: var_fSdesc,
        fCats: var_fCats);
  }

  @protected
  TagGroup sse_decode_tag_group(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_groupName = sse_decode_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    return TagGroup(groupName: var_groupName, tags: var_tags);
  }

  @protected
  TagSuggestion sse_decode_tag_suggestion(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_raw = sse_decode_String(deserializer);
    var var_translated = sse_decode_String(deserializer);
    return TagSuggestion(raw: var_raw, translated: var_translated);
  }

  @protected
  TorrentItem sse_decode_torrent_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_posted = sse_decode_String(deserializer);
    var var_sizeText = sse_decode_String(deserializer);
    var var_seeds = sse_decode_String(deserializer);
    var var_peers = sse_decode_String(deserializer);
    var var_downloads = sse_decode_String(deserializer);
    var var_uploader = sse_decode_String(deserializer);
    var var_hash = sse_decode_String(deserializer);
    var var_token = sse_decode_String(deserializer);
    return TorrentItem(
        name: var_name,
        posted: var_posted,
        sizeText: var_sizeText,
        seeds: var_seeds,
        peers: var_peers,
        downloads: var_downloads,
        uploader: var_uploader,
        hash: var_hash,
        token: var_token);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
      sse_encode_DartFn_Inputs_u_64_opt_box_autoadd_u_64_Output_unit_AnyhowException(
          FutureOr<void> Function(BigInt, BigInt?) self,
          SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_DartOpaque(
        encode_DartFn_Inputs_u_64_opt_box_autoadd_u_64_Output_unit_AnyhowException(
            self),
        serializer);
  }

  @protected
  void sse_encode_DartOpaque(Object self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_isize(
        PlatformPointerUtil.ptrToPlatformInt64(encodeDartOpaque(
            self, portManager.dartHandlerPort, generalizedFrbRustBinding)),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_search_options(
      SearchOptions self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_search_options(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_download_task(DownloadTask self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.gid, serializer);
    sse_encode_String(self.token, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_u_32(self.totalPages, serializer);
    sse_encode_u_32(self.downloadedPages, serializer);
    sse_encode_i_32(self.status, serializer);
    sse_encode_opt_String(self.errorMsg, serializer);
  }

  @protected
  void sse_encode_gallery_comment(
      GalleryComment self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.author, serializer);
    sse_encode_String(self.time, serializer);
    sse_encode_String(self.content, serializer);
  }

  @protected
  void sse_encode_gallery_detail(GalleryDetail self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.titleJpn, serializer);
    sse_encode_String(self.coverUrl, serializer);
    sse_encode_String(self.uploader, serializer);
    sse_encode_String(self.rating, serializer);
    sse_encode_String(self.language, serializer);
    sse_encode_String(self.fileSize, serializer);
    sse_encode_String(self.postDate, serializer);
    sse_encode_String(self.favoritesCount, serializer);
    sse_encode_String(self.torrentCount, serializer);
    sse_encode_list_tag_group(self.tagGroups, serializer);
    sse_encode_u_32(self.totalPages, serializer);
    sse_encode_list_String(self.imageUrls, serializer);
    sse_encode_list_gallery_thumbnail(self.thumbnails, serializer);
    sse_encode_list_gallery_comment(self.comments, serializer);
    sse_encode_bool(self.isFavorited, serializer);
  }

  @protected
  void sse_encode_gallery_item(GalleryItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.gid, serializer);
    sse_encode_String(self.token, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.thumbUrl, serializer);
    sse_encode_String(self.category, serializer);
    sse_encode_String(self.uploader, serializer);
    sse_encode_String(self.postDate, serializer);
  }

  @protected
  void sse_encode_gallery_page(GalleryPage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_gallery_item(self.items, serializer);
    sse_encode_opt_String(self.nextUrl, serializer);
  }

  @protected
  void sse_encode_gallery_thumbnail(
      GalleryThumbnail self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.url, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_u_32(self.offsetX, serializer);
    sse_encode_u_32(self.offsetY, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_isize(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_download_task(
      List<DownloadTask> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_download_task(item, serializer);
    }
  }

  @protected
  void sse_encode_list_gallery_comment(
      List<GalleryComment> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_gallery_comment(item, serializer);
    }
  }

  @protected
  void sse_encode_list_gallery_item(
      List<GalleryItem> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_gallery_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_gallery_thumbnail(
      List<GalleryThumbnail> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_gallery_thumbnail(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_tag_group(
      List<TagGroup> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_tag_group(item, serializer);
    }
  }

  @protected
  void sse_encode_list_tag_suggestion(
      List<TagSuggestion> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_tag_suggestion(item, serializer);
    }
  }

  @protected
  void sse_encode_list_torrent_item(
      List<TorrentItem> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_torrent_item(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_search_options(
      SearchOptions? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_search_options(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_search_options(SearchOptions self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.fSname, serializer);
    sse_encode_bool(self.fStags, serializer);
    sse_encode_bool(self.fSdesc, serializer);
    sse_encode_opt_box_autoadd_u_32(self.fCats, serializer);
  }

  @protected
  void sse_encode_tag_group(TagGroup self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.groupName, serializer);
    sse_encode_list_String(self.tags, serializer);
  }

  @protected
  void sse_encode_tag_suggestion(TagSuggestion self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.raw, serializer);
    sse_encode_String(self.translated, serializer);
  }

  @protected
  void sse_encode_torrent_item(TorrentItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.posted, serializer);
    sse_encode_String(self.sizeText, serializer);
    sse_encode_String(self.seeds, serializer);
    sse_encode_String(self.peers, serializer);
    sse_encode_String(self.downloads, serializer);
    sse_encode_String(self.uploader, serializer);
    sse_encode_String(self.hash, serializer);
    sse_encode_String(self.token, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}
