// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class EhWebConfig {
  final String loadHath;
  final String imageSize;
  final String imageWidth;
  final String imageHeight;
  final String titleDisplay;
  final String archiverSettings;
  final String displayMode;
  final List<String> favoriteNames;
  final Map<String, String> rawParams;

  const EhWebConfig({
    required this.loadHath,
    required this.imageSize,
    required this.imageWidth,
    required this.imageHeight,
    required this.titleDisplay,
    required this.archiverSettings,
    required this.displayMode,
    required this.favoriteNames,
    required this.rawParams,
  });

  @override
  int get hashCode =>
      loadHath.hashCode ^
      imageSize.hashCode ^
      imageWidth.hashCode ^
      imageHeight.hashCode ^
      titleDisplay.hashCode ^
      archiverSettings.hashCode ^
      displayMode.hashCode ^
      favoriteNames.hashCode ^
      rawParams.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EhWebConfig &&
          runtimeType == other.runtimeType &&
          loadHath == other.loadHath &&
          imageSize == other.imageSize &&
          imageWidth == other.imageWidth &&
          imageHeight == other.imageHeight &&
          titleDisplay == other.titleDisplay &&
          archiverSettings == other.archiverSettings &&
          displayMode == other.displayMode &&
          favoriteNames == other.favoriteNames &&
          rawParams == other.rawParams;
}

class GalleryComment {
  final String author;
  final String time;
  final String content;

  /// E-Hentai comment id (from `<div class="c1" id="c_123456">`), 0 when absent.
  final BigInt id;

  /// Comment vote score (upvotes - downvotes), 0 when unavailable.
  final int score;

  /// Vote link parsed from the detail page HTML (`...act=vote&comment_id=...&vote=1`).
  /// Relative URLs are completed against the site URL at vote time.
  final String voteUrl;

  const GalleryComment({
    required this.author,
    required this.time,
    required this.content,
    required this.id,
    required this.score,
    required this.voteUrl,
  });

  @override
  int get hashCode =>
      author.hashCode ^
      time.hashCode ^
      content.hashCode ^
      id.hashCode ^
      score.hashCode ^
      voteUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GalleryComment &&
          runtimeType == other.runtimeType &&
          author == other.author &&
          time == other.time &&
          content == other.content &&
          id == other.id &&
          score == other.score &&
          voteUrl == other.voteUrl;
}

class GalleryDetail {
  final String id;
  final String title;
  final String titleJpn;
  final String coverUrl;
  final String uploader;
  final String rating;
  final String language;
  final String fileSize;
  final String postDate;
  final String favoritesCount;
  final String torrentCount;
  final List<TagGroup> tagGroups;
  final int totalPages;
  final List<String> imageUrls;
  final List<GalleryThumbnail> thumbnails;
  final List<GalleryComment> comments;
  final bool isFavorited;

  const GalleryDetail({
    required this.id,
    required this.title,
    required this.titleJpn,
    required this.coverUrl,
    required this.uploader,
    required this.rating,
    required this.language,
    required this.fileSize,
    required this.postDate,
    required this.favoritesCount,
    required this.torrentCount,
    required this.tagGroups,
    required this.totalPages,
    required this.imageUrls,
    required this.thumbnails,
    required this.comments,
    required this.isFavorited,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      titleJpn.hashCode ^
      coverUrl.hashCode ^
      uploader.hashCode ^
      rating.hashCode ^
      language.hashCode ^
      fileSize.hashCode ^
      postDate.hashCode ^
      favoritesCount.hashCode ^
      torrentCount.hashCode ^
      tagGroups.hashCode ^
      totalPages.hashCode ^
      imageUrls.hashCode ^
      thumbnails.hashCode ^
      comments.hashCode ^
      isFavorited.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GalleryDetail &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          titleJpn == other.titleJpn &&
          coverUrl == other.coverUrl &&
          uploader == other.uploader &&
          rating == other.rating &&
          language == other.language &&
          fileSize == other.fileSize &&
          postDate == other.postDate &&
          favoritesCount == other.favoritesCount &&
          torrentCount == other.torrentCount &&
          tagGroups == other.tagGroups &&
          totalPages == other.totalPages &&
          imageUrls == other.imageUrls &&
          thumbnails == other.thumbnails &&
          comments == other.comments &&
          isFavorited == other.isFavorited;
}

class GalleryItem {
  final String gid;
  final String token;
  final String title;
  final String thumbUrl;
  final String category;
  final String uploader;
  final String postDate;

  const GalleryItem({
    required this.gid,
    required this.token,
    required this.title,
    required this.thumbUrl,
    required this.category,
    required this.uploader,
    required this.postDate,
  });

  @override
  int get hashCode =>
      gid.hashCode ^
      token.hashCode ^
      title.hashCode ^
      thumbUrl.hashCode ^
      category.hashCode ^
      uploader.hashCode ^
      postDate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GalleryItem &&
          runtimeType == other.runtimeType &&
          gid == other.gid &&
          token == other.token &&
          title == other.title &&
          thumbUrl == other.thumbUrl &&
          category == other.category &&
          uploader == other.uploader &&
          postDate == other.postDate;
}

class GalleryPage {
  final List<GalleryItem> items;
  final String? nextUrl;

  const GalleryPage({
    required this.items,
    this.nextUrl,
  });

  @override
  int get hashCode => items.hashCode ^ nextUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GalleryPage &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          nextUrl == other.nextUrl;
}

class GalleryThumbnail {
  final String url;
  final int width;
  final int height;
  final int offsetX;
  final int offsetY;

  const GalleryThumbnail({
    required this.url,
    required this.width,
    required this.height,
    required this.offsetX,
    required this.offsetY,
  });

  @override
  int get hashCode =>
      url.hashCode ^
      width.hashCode ^
      height.hashCode ^
      offsetX.hashCode ^
      offsetY.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GalleryThumbnail &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          width == other.width &&
          height == other.height &&
          offsetX == other.offsetX &&
          offsetY == other.offsetY;
}

class TagGroup {
  final String groupName;
  final List<String> tags;

  const TagGroup({
    required this.groupName,
    required this.tags,
  });

  @override
  int get hashCode => groupName.hashCode ^ tags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TagGroup &&
          runtimeType == other.runtimeType &&
          groupName == other.groupName &&
          tags == other.tags;
}

/// A single torrent entry from the gallery torrents popup (/gallerytorrents.php).
class TorrentItem {
  final String name;
  final String posted;
  final String sizeText;
  final String seeds;
  final String peers;
  final String downloads;
  final String uploader;
  final String hash;
  final String token;

  const TorrentItem({
    required this.name,
    required this.posted,
    required this.sizeText,
    required this.seeds,
    required this.peers,
    required this.downloads,
    required this.uploader,
    required this.hash,
    required this.token,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      posted.hashCode ^
      sizeText.hashCode ^
      seeds.hashCode ^
      peers.hashCode ^
      downloads.hashCode ^
      uploader.hashCode ^
      hash.hashCode ^
      token.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TorrentItem &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          posted == other.posted &&
          sizeText == other.sizeText &&
          seeds == other.seeds &&
          peers == other.peers &&
          downloads == other.downloads &&
          uploader == other.uploader &&
          hash == other.hash &&
          token == other.token;
}
