// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A raw E-Hentai tag matched by its Chinese translation, e.g.
/// raw "parody:genshin impact" translated "原神".
class TagSuggestion {
  final String raw;
  final String translated;

  const TagSuggestion({
    required this.raw,
    required this.translated,
  });

  @override
  int get hashCode => raw.hashCode ^ translated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TagSuggestion &&
          runtimeType == other.runtimeType &&
          raw == other.raw &&
          translated == other.translated;
}
